# -*- coding: utf-8 -*-
"""TSD_DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyO0XzjzLNcruedMjcRI27ErTyDeGjCS

Import les modèle et bibliotheques
"""

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold,
    GridSearchCV, RandomizedSearchCV
)
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, roc_curve, confusion_matrix, classification_report,
    make_scorer
)

# Modèles
from sklearn.linear_model import LogisticRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
import xgboost as xgb

import warnings
warnings.filterwarnings('ignore')

# Configuration
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")
np.random.seed(42)

print("Imports terminés")

"""Chargement des données"""

file_path = "donnee_etu.xlsx"

train_df = pd.read_excel(file_path, sheet_name="train")
val_df   = pd.read_excel(file_path, sheet_name="Validation")
print("Train shape:", train_df.shape)
print("Validation shape:", val_df.shape)

print("\nTrain head:")
display(train_df.head())

print("\nValidation head:")
display(val_df.head())

print("\nTrain dtypes:")
print(train_df.dtypes)

"""Définition du pipeline de pré-traitement"""

# 2. Supprimer la colonne Type de la validation (toutes les valeurs NaN)
if "Type" in val_df.columns:
  val_df = val_df.drop(columns=["Type"])

# 3. Définir les groupes de caractéristiques
categorical_cols = ["marqueur 2", "marqueur 3", "marqueur 4", "marqueur 5"]
numeric_cols = ["age", "marqueur 6", "marqueur 7", "marqueur 8", "marqueur 9"]

# 4. Définir les transformer
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(drop="if_binary", handle_unknown='ignore')) # Ajout de handle_unknown=“ignore”
])

# 5. Créer le ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

print("Pipeline de prétraitement mis à jour et prêt.")

"""Obtentions du valeurs de X & Y"""

# Garder les étiquettes originales (1-indexées) comme demandé par l'utilisateur
train_df["Type"] = train_df["Type"]

# Définir correctement X et y
X = train_df.drop(columns=["Type"])
y = train_df["Type"]

# Ensemble de validation (colonne Type déjà supprimée précédemment)
X_val = val_df.copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_val shape:", X_val.shape)
print("Unique labels in y:", sorted(y.unique()))

"""Entrainer les données"""

# Division entre entraînement et test (même structure que le notebook sur le diabète)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=0
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)
print(sorted(y_train.unique()))

"""ML modèle RÉGRESSION LOGISTIQUE"""

print("="*80)
print("RÉGRESSION LOGISTIQUE MULTINOMIALE - Modèle de référence")
print("="*80)

# Appliquer le prétraitement (OHE + mise à l'échelle)
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled = preprocessor.transform(X_test)

# Régression logistique multiclasses
logreg = LogisticRegression(
    random_state=42,
    max_iter=1000,
    multi_class="multinomial",
    solver="lbfgs"
)
logreg.fit(X_train_scaled, y_train)

# Prédictions
y_pred_logreg = logreg.predict(X_test_scaled)
y_proba_logreg = logreg.predict_proba(X_test_scaled)

# Métriques
print("\n RESULTS (test set):")
print(f"  Accuracy:     {accuracy_score(y_test, y_pred_logreg):.3f}")
print(f"  F1-macro:     {f1_score(y_test, y_pred_logreg, average='macro'):.3f}")

print("\n Classification report:")
print(classification_report(y_test, y_pred_logreg))

print("\n Confusion matrix:")
print(confusion_matrix(y_test, y_pred_logreg))

# Validation croisée
cv_scores = cross_val_score(
    logreg,
    X_train_scaled,
    y_train,
    cv=5,
    scoring="f1_macro"
)

print(f"\n Cross-validation (5-fold):")
print(f"  F1-macro: {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")

# Coefficients
print("\n Feature importance (coefficients):")

# Les noms des caractéristiques transformées
feature_names = preprocessor.get_feature_names_out()

coef_df = pd.DataFrame(
    logreg.coef_,
    columns=feature_names,
    index=[f'Class_{c}' for c in sorted(y.unique())] # Ensure index matches 1-indexed classes
)

print(coef_df)

"""ML modèle KNN"""

print("="*80)
print("  K-NEAREST NEIGHBORS (KNN) - Multiclasses")
print("="*80)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score

# Pipeline KNN + prétraitement
knn_model = Pipeline([
    ("preprocess", preprocessor),
    ("clf", KNeighborsClassifier())
])

# Grille d'hyperparamètres
param_grid_knn = {
    'clf__n_neighbors': [3, 5, 7, 9, 11, 13, 15],
    'clf__weights': ['uniform', 'distance'],
    'clf__metric': ['euclidean', 'manhattan']
}

# GridSearchCV
grid_knn = GridSearchCV(
    knn_model,
    param_grid_knn,
    cv=5,
    scoring='f1_macro',
    n_jobs=-1
)

grid_knn.fit(X_train, y_train)

print("\nMeilleurs hyperparamètres:")
print(grid_knn.best_params_)
print(f"Score CV (F1-macro): {grid_knn.best_score_:.3f}")

# Ensemble de test
y_pred_knn = grid_knn.predict(X_test)
print(f"Score test (F1-macro): {f1_score(y_test, y_pred_knn, average='macro'):.3f}")

"""ML modèle RANDOM FOREST"""

print("="*80)
print("RANDOM FOREST - Multiclasses (CV stable)")
print("="*80)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score
from scipy.stats import randint

# SCV stratifié à 2 plis (la seule option sûre avec des petites classes)
cv = StratifiedKFold(n_splits=2, shuffle=True, random_state=42)

# Pipeline RF + prétraitement
rf_model = Pipeline([
    ("preprocess", preprocessor),
    ("clf", RandomForestClassifier(random_state=42, n_jobs=-1))
])

# Distributions des hyperparamètres
param_dist_rf = {
    'clf__n_estimators': [100, 200, 300, 500],
    'clf__max_depth': [None, 5, 10, 20, 30],
    'clf__min_samples_split': randint(2, 20),
    'clf__min_samples_leaf': randint(1, 10),
    'clf__max_features': ['sqrt', 'log2', None],
    'clf__bootstrap': [True, False]
}

# RandomizedSearchCV
random_rf = RandomizedSearchCV(
    rf_model,
    param_dist_rf,
    n_iter=50,
    cv=cv,                    # ← 2-fold stratified CV
    scoring='f1_macro',
    n_jobs=-1,
    random_state=42
)

# Forme
random_rf.fit(X_train, y_train)

print("\nMeilleurs hyperparamètres:")
print(random_rf.best_params_)
print(f"Score CV (F1-macro): {random_rf.best_score_:.3f}")

# Ensemble de test
y_pred_rf = random_rf.predict(X_test)
print(f"Score test (F1-macro): {f1_score(y_test, y_pred_rf, average='macro'):.3f}")

"""ML modèle SVM"""

print("="*80)
print("SUPPORT VECTOR MACHINE (SVM) - Multiclasses (Stable CV)")
print("="*80)

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score, make_scorer

# Scorer personnalisé pour éviter les NaN
scorer = make_scorer(f1_score, average='macro', zero_division=0)

# 2-fold stratified CV
cv = StratifiedKFold(n_splits=2, shuffle=True, random_state=42)

# Pipeline
svm_model = Pipeline([
    ("preprocess", preprocessor),
    ("clf", SVC(kernel="rbf", probability=True, class_weight="balanced"))
])

# Hyperparamètres
param_grid_svm = {
    "clf__C": [0.1, 1, 10, 50, 100],
    "clf__gamma": ["scale", 0.01, 0.001, 0.0001]
}

# GridSearchCV
grid_svm = GridSearchCV(
    svm_model,
    param_grid_svm,
    cv=cv,
    scoring=scorer,   # ← FIXER
    n_jobs=-1
)

grid_svm.fit(X_train, y_train)

print("\nMeilleurs hyperparamètres:")
print(grid_svm.best_params_)
print(f"Score CV (F1-macro): {grid_svm.best_score_:.3f}")

y_pred_svm = grid_svm.predict(X_test)
print(f"Score test (F1-macro): {f1_score(y_test, y_pred_svm, average='macro'):.3f}")

"""ML modèle XGBoost"""

print("="*80)
print("XGBOOST (Gradient Boosting) - Multiclasses")
print("="*80)

from xgboost import XGBClassifier
#from sklearn.model_selection import GridSearchCV, StratifiedKFold
#from sklearn.pipeline import Pipeline
#from sklearn.metrics import f1_score, make_scorer

# Scorer personnalisé pour éviter les NaN lorsqu'une classe est manquante dans un fold
scorer = make_scorer(f1_score, average='macro', zero_division=0)

# 2-fold stratified CV (seule option sûre avec des classes minuscules)
cv = StratifiedKFold(n_splits=2, shuffle=True, random_state=42)

# Create 0-indexed labels for XGBoost training only
y_train_xgb = y_train - 1
y_test_xgb = y_test - 1

# Pipeline XGB + prétraitement
xgb_model = Pipeline([
    ("preprocess", preprocessor),
    ("clf", XGBClassifier(
        objective="multi:softprob",
        num_class=len(y_train_xgb.unique()), # Use 0-indexed unique for num_class
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1
    ))
])

# Grille des Hyperparamètres
param_grid_xgb = {
    "clf__n_estimators": [100, 200, 300],
    "clf__max_depth": [3, 4, 5, 6],
    "clf__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "clf__subsample": [0.6, 0.8, 1.0],
    "clf__colsample_bytree": [0.6, 0.8, 1.0],
    "clf__gamma": [0, 1, 5]
}

# GridSearchCV
grid_xgb = GridSearchCV(
    xgb_model,
    param_grid_xgb,
    cv=cv,
    scoring=scorer,
    n_jobs=-1
)

grid_xgb.fit(X_train, y_train_xgb) # Fit with 0-indexed y_train_xgb

print("\nMeilleurs hyperparamètres:")
print(grid_xgb.best_params_)
print(f"Score CV (F1-macro): {grid_xgb.best_score_:.3f}")

# Test set - predict and convert back to 1-indexed for evaluation
y_pred_xgb = grid_xgb.predict(X_test) + 1 # Add 1 to convert predictions back to 1-indexed
print(f"Score test (F1-macro): {f1_score(y_test, y_pred_xgb, average='macro'):.3f}")

"""Comparaison de ML modèles"""

from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import label_binarize

print("="*80)
print("COMPARAISON DES ML MODÈLES")
print("="*80)

# Binarisation des labels pour ROC-AUC multiclasses (labels 1-indexées pour la comparaison globale)
y_test_bin_global = label_binarize(y_test, classes=sorted(y.unique()))

models_comparison = {
    'Logistic Regression': {
        'model': logreg,
        'X_test': X_test, # Pass raw X_test (DataFrame) pour la transformation explicite ci-dessous
        'y_test_for_proba': y_test # 1-indexed
    },
    'KNN': {
        'model': grid_knn.best_estimator_,
        'X_test': X_test,
        'y_test_for_proba': y_test # 1-indexed
    },
    'Random Forest': {
        'model': random_rf.best_estimator_,
        'X_test': X_test,
        'y_test_for_proba': y_test # 1-indexed
    },
    'SVM': {
        'model': grid_svm.best_estimator_,
        'X_test': X_test,
        'y_test_for_proba': y_test # 1-indexed
    },
    'XGBoost': {
        'model': grid_xgb.best_estimator_,
        'X_test': X_test,
        'y_test_for_proba': y_test - 1 # 0-indexed for XGBoost proba matching
    }
}

results = []

for name, info in models_comparison.items():
    model = info['model']
    X_te_raw = info['X_test']
    y_te_for_proba = info['y_test_for_proba']

    # Déterminez les données d'entrée appropriées pour le modèle (transformées pour l'exécution autonome, brutes pour les pipelines)
    X_te_input = None
    if not isinstance(model, Pipeline):
        X_te_input = preprocessor.transform(X_te_raw)
    else:
        X_te_input = X_te_raw # Pipelines handle internal preprocessing

    # Debug print statement
    print(f"\nDEBUG: Model: {name}, X_te_input type: {type(X_te_input)}, X_te_input shape: {X_te_input.shape}")
    # if hasattr(X_te_input, 'head'): print(f"X_te_input head: {X_te_input.head()}")
    # else: print(f"X_te_input first row: {X_te_input[0] if len(X_te_input) > 0 else 'N/A'}")

    # Predictions (Tous les modèles doivent, si possible, fournir des prévisions en indice 1, ou être convertis en indice 1)
    y_pred = model.predict(X_te_input)
    if name == 'XGBoost': # Convert XGBoost predictions back to 1-indexed for f1_score
        y_pred = y_pred + 1

    # Probabilités pour ROC-AUC OVR (si disponible)
    try:
        y_proba = model.predict_proba(X_te_input)
        # For XGBoost, y_proba is 0-indexed, so y_test_bin should also be 0-indexed
        y_test_bin_current = label_binarize(y_te_for_proba, classes=sorted(y_te_for_proba.unique()))
        roc_auc = roc_auc_score(y_test_bin_current, y_proba, multi_class='ovr')
    except Exception as e:
        roc_auc = None
        print(f"Warning: Could not calculate ROC-AUC for {name} - {e}")

    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Balanced Accuracy': balanced_accuracy_score(y_test, y_pred),
        'F1-macro': f1_score(y_test, y_pred, average='macro'),
        'ROC-AUC OVR': roc_auc
    })

results_df = pd.DataFrame(results).sort_values('F1-macro', ascending=False)
print("\nTABLEAU RÉCAPITULATIF:")
print(results_df.to_string(index=False))

"""# 🧠 Deep Learning ( Réseau de neurones [MLP, PyTorch])


**Plan :**

Manipulation de tenseurs et couches denses sur données tabulaires.
---

Imports
"""

import random

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

torch.manual_seed(0)
np.random.seed(0)
random.seed(0)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

print(f"PyTorch version : {torch.__version__}")
print(f"GPU disponible  : {torch.cuda.is_available()}")
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device utilisé  : {DEVICE}")

"""Convertissez les données prétraitées en tenseurs PyTorch"""

# Convert to tensors
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor  = torch.tensor(X_test_scaled,  dtype=torch.float32)

# Adjust target labels from 1-indexed to 0-indexed for CrossEntropyLoss
y_train_tensor = torch.tensor(y_train.values - 1, dtype=torch.long)
y_test_tensor  = torch.tensor(y_test.values - 1,  dtype=torch.long)

# Create datasets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset  = TensorDataset(X_test_tensor,  y_test_tensor)

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False)

print(f"Unique labels in y_train_tensor after adjustment: {y_train_tensor.unique().tolist()}")
print(f"Unique labels in y_test_tensor after adjustment: {y_test_tensor.unique().tolist()}")
len(train_dataset), len(test_dataset)

"""Définir l'architecture de MLP"""

input_size  = X_train_scaled.shape[1]   # 12
num_classes = len(y_train.unique())     # 6

class MLP(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.Tanh(),          # first non-linearity
            nn.Dropout(0.1),    # regularization
            nn.Linear(128, 64),
            nn.ReLU(),          # second non-linearity
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        return self.model(x)

model = MLP(input_size, num_classes).to(DEVICE)
model

"""Fonction de perte, optimiseur et boucle d'apprentissage"""

# Fonction de perte pour la classification multicatégorielle
criterion = nn.CrossEntropyLoss()

# 2) Optimiseur (Adam) avec un taux d'apprentissage donné
learning_rate = 0.001
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
print("Learning rate:", learning_rate)

# 3) Fonction permettant d'entraîner le modèle pendant UNE époque
def train_one_epoch(model, loader, optimizer, criterion):
    model.train()
    total_loss = 0.0

    for X_batch, y_batch in loader:
        optimizer.zero_grad()          # reset gradients
        outputs = model(X_batch)       # forward pass
        loss = criterion(outputs, y_batch)  # compute loss
        loss.backward()                # backpropagation
        optimizer.step()               # update weights

        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    return avg_loss

# 4) Fonction permettant d'évaluer la précision d'un chargeur
def evaluate(model, loader):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for X_batch, y_batch in loader:
            outputs = model(X_batch)
            _, predicted = torch.max(outputs, 1)
            total += y_batch.size(0)
            correct += (predicted == y_batch).sum().item()

    accuracy = correct / total
    return accuracy

# 5) Entraînez le modèle pendant plusieurs époques et surveillez la perte et la précision
epochs = 30 # Increased number of epochs

for epoch in range(epochs):
    train_loss = train_one_epoch(model, train_loader, optimizer, criterion)
    test_acc = evaluate(model, test_loader)
    print(f"Epoch {epoch+1}/{epochs} - Loss: {train_loss:.4f} - Test Acc: {test_acc:.4f}")

# Enregistrer la précision finale du réseau neuronal pour une comparaison ultérieure avec les modèles d'apprentissage automatique
nn_accuracy = evaluate(model, test_loader)
print("Final Neural Network Accuracy:", nn_accuracy)

"""Matrice de confusion + Rapport de classification"""

# Get predictions on the test set
model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.to(DEVICE)
        y_batch = y_batch.to(DEVICE)

        outputs = model(X_batch)
        _, predicted = torch.max(outputs, 1)

        all_preds.append(predicted.cpu().numpy())
        all_labels.append(y_batch.cpu().numpy())

y_true = np.concatenate(all_labels)
y_pred = np.concatenate(all_preds)

print("y_true shape:", y_true.shape)
print("y_pred shape:", y_pred.shape)

# Classification report

# Remember: labels are 0–5, original classes were 1–6
target_names = [f"Class {i}" for i in range(1, 7)]

print(classification_report(y_true, y_pred, target_names=target_names))

# Confusion matrix (numeric)

cm = confusion_matrix(y_true, y_pred)
print("Confusion matrix:\n", cm)

# Confusion matrix (heatmap)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=target_names,
            yticklabels=target_names)
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix - Neural Network")
plt.tight_layout()
plt.show()

nn_accuracy = evaluate(model, test_loader)
print("Final Neural Network Accuracy:", nn_accuracy)

"""##Expérimentation de modèle

1. *Varier l'architecture*
"""

# 1.1 Helper function to run an experiment

def run_experiment(model_class, description, lr=0.001, epochs=30):
    model = model_class(input_size, num_classes).to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_acc = 0.0
    for epoch in range(epochs):
        train_loss = train_one_epoch(model, train_loader, optimizer, criterion)
        test_acc   = evaluate(model, test_loader)
        best_acc = max(best_acc, test_acc)
        print(f"[{description}] Epoch {epoch+1}/{epochs} - Loss: {train_loss:.4f} - Test Acc: {test_acc:.4f}")

    print(f"Best accuracy for {description}: {best_acc:.4f}")
    return best_acc

# 1.2 Define alternative architectures

class MLP_small(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.Tanh(),
            nn.Dropout(0.1),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, num_classes)
        )
    def forward(self, x):
        return self.model(x)


class MLP_big(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 256),
            nn.Tanh(),
            nn.Dropout(0.1),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )
    def forward(self, x):
        return self.model(x)

# 1.3 Run the architecture experiments

print("=== Architecture experiments ===")

acc_small = run_experiment(MLP_small, "Small MLP (64-32)", lr=0.001, epochs=30)
acc_base  = run_experiment(MLP,       "Base MLP (128-64)", lr=0.001, epochs=30)
acc_big   = run_experiment(MLP_big,   "Big MLP (256-128)", lr=0.001, epochs=30)

"""2. *Modifier le Dropout*"""

# 2.1 Define MLP variants with different dropout

class MLP_dropout_0(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.Tanh(),
            # no dropout
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)


class MLP_dropout_01(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.Tanh(),
            nn.Dropout(0.1),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)


class MLP_dropout_05(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.Tanh(),
            nn.Dropout(0.5),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)

# 2.2 Run the dropout experiments

print("=== Dropout experiments ===")

acc_do_0  = run_experiment(MLP_dropout_0,  "Dropout 0.0",  lr=0.001, epochs=30)
acc_do_01 = run_experiment(MLP_dropout_01, "Dropout 0.1",  lr=0.001, epochs=30)
acc_do_05 = run_experiment(MLP_dropout_05, "Dropout 0.5",  lr=0.001, epochs=30)

"""3. *Varier les fonctions d'activation*"""

# 3.1 Define activation variants

class MLP_relu_relu(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)


class MLP_tanh_tanh(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.Tanh(),
            nn.Dropout(0.1),
            nn.Linear(128, 64),
            nn.Tanh(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)


class MLP_tanh_gelu(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.Tanh(),
            nn.Dropout(0.1),
            nn.Linear(128, 64),
            nn.GELU(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)

# 3.2 — Run the activation experiments

print("=== Activation function experiments ===")

acc_relu_relu = run_experiment(MLP_relu_relu, "ReLU-ReLU",    lr=0.001, epochs=30)
acc_tanh_tanh = run_experiment(MLP_tanh_tanh, "Tanh-Tanh",    lr=0.001, epochs=30)
acc_tanh_relu = run_experiment(MLP,           "Tanh-ReLU",    lr=0.001, epochs=30)
acc_tanh_gelu = run_experiment(MLP_tanh_gelu, "Tanh-GELU",    lr=0.001, epochs=30)

"""4. *Vary the Learning Rate*"""

print("=== Learning rate experiments ===")

acc_lr_0005   = run_experiment(MLP, "LR = 0.005",   lr=0.005,   epochs=30)
acc_lr_0001   = run_experiment(MLP, "LR = 0.001",   lr=0.001,   epochs=30)
acc_lr_00005  = run_experiment(MLP, "LR = 0.0005",  lr=0.0005,  epochs=30)  # <-- added
acc_lr_00001  = run_experiment(MLP, "LR = 0.0001",  lr=0.0001,  epochs=30)

"""5. *Résumé des expériences*"""

import pandas as pd

results_exp = [
    # Architecture
    ["Architecture", "Small (64-32)",      acc_small],
    ["Architecture", "Base (128-64)",      acc_base],
    ["Architecture", "Big (256-128)",      acc_big],

    # Dropout
    ["Dropout",      "0.0",                acc_do_0],
    ["Dropout",      "0.1",                acc_do_01],
    ["Dropout",      "0.5",                acc_do_05],

    # Activation
    ["Activation",   "ReLU-ReLU",          acc_relu_relu],
    ["Activation",   "Tanh-Tanh",          acc_tanh_tanh],
    ["Activation",   "Tanh-ReLU (base)",   acc_tanh_relu],
    ["Activation",   "Tanh-GELU",          acc_tanh_gelu],

    # Learning rate
    ["Learning rate","0.005",              acc_lr_0005],
    ["Learning rate","0.001",              acc_lr_0001],
    ["Learning rate","0.0005",             acc_lr_00005],
    ["Learning rate","0.0001",             acc_lr_00001],
]

df_exp = pd.DataFrame(results_exp,
                        columns=["Experiment type", "Setting", "Best accuracy"])

df_exp

"""6. *Modèle combiné « meilleure configuration »*

V1
"""

class MLP_best(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.Tanh(),
            nn.Dropout(0.5),
            nn.Linear(64, 32),
            nn.Tanh(),
            nn.Linear(32, num_classes)
        )
    def forward(self, x):
        return self.model(x)

acc_best = run_experiment(
    MLP_best,
    "Best config (64-32, dropout 0.5, Tanh-Tanh, LR=0.0005)",
    lr=0.0005,
    epochs=30
)

"""V2 MLP_best_v2 — small architecture, dropout 0.1, Tanh–Tanh, LR=0.0005"""

class MLP_best_v2(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.Tanh(),
            nn.Dropout(0.1),   # moderate dropout
            nn.Linear(64, 32),
            nn.Tanh(),
            nn.Linear(32, num_classes)
        )
    def forward(self, x):
        return self.model(x)

acc_best_v2 = run_experiment(
    MLP_best_v2,
    "Best config v2 (64-32, dropout 0.1, Tanh-Tanh, LR=0.0005)",
    lr=0.0005,
    epochs=30
)

"""MLP_best_v3 — small architecture, NO dropout, Tanh–Tanh, LR=0.0005"""

class MLP_best_v3(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.Tanh(),
            # no dropout
            nn.Linear(64, 32),
            nn.Tanh(),
            nn.Linear(32, num_classes)
        )
    def forward(self, x):
        return self.model(x)

acc_best_v3 = run_experiment(
    MLP_best_v3,
    "Best config v3 (64-32, no dropout, Tanh-Tanh, LR=0.0005)",
    lr=0.0005,
    epochs=30
)

"""Plusieurs configurations combinées ont été testées en utilisant les meilleurs hyperparamètres individuels. Aucun des modèles combinés n'a surpassé les meilleurs réglages individuels. Le meilleur modèle combiné (architecture 64–32, activation Tanh–Tanh, LR = 0,0005, sans dropout) a atteint une précision de 0,7917. Cela confirme que les effets des hyperparamètres peuvent ne pas se combiner de manière linéaire : certaines combinaisons réduisent la capacité du modèle ou ralentissent l'apprentissage, ce qui conduit à un sous-ajustement. Les meilleurs résultats ont été obtenus en ajustant chaque hyperparamètre indépendamment plutôt qu'en les fusionnant en une seule configuration.

## Comparaison de modèles MLP & ML Classique
"""

# Extract the best ML accuracy

best_ml_row = results_df.loc[results_df['Accuracy'].idxmax()]
best_ml_model = best_ml_row['Model']
best_ml_acc = best_ml_row['Accuracy']

# Extract the best MLP accuracy

nn_results = {
    "Small MLP (64-32)": acc_small,
    "Dropout 0.5 MLP": acc_do_05,
    "Tanh-Tanh MLP": acc_tanh_tanh,
    "LR=0.0005 MLP": acc_lr_00005,
    "Combined v1": acc_best,
    "Combined v2": acc_best_v2,
    "Combined v3": acc_best_v3
}

best_nn_model = max(nn_results, key=nn_results.get)
best_nn_acc = nn_results[best_nn_model]

# Unify the 2

df_compare_ml_nn = pd.DataFrame([
    [best_ml_model + " (ML)", best_ml_acc],
    [best_nn_model + " (MLP)", best_nn_acc]
], columns=["Model", "Accuracy"])

df_compare_ml_nn

"""*Comparaison Globale*"""

df_all = results_df[['Model', 'Accuracy']].copy()  # ML models

# Add NN models
for name, acc in nn_results.items():
    df_all.loc[len(df_all)] = [name + " (MLP)", acc]

df_all.sort_values('Accuracy', ascending=False)

"""Les réseaux neuronaux n'ont pas surpassé les méthodes classiques d'apprentissage automatique sur cet ensemble de données.
L'ensemble de données est de petite taille et structuré, ce qui favorise les modèles basés sur des arbres, tels que RandomForest.
Les réseaux neuronaux n'atteignent des performances comparables qu'après un réglage approfondi des hyperparamètres.

## Prédiction
"""

print("=== FINAL ALIGNMENT CHECK BEFORE PREDICTION ===")

# 1. Shapes
print("X_train_scaled:", X_train_scaled.shape)
print("X_test_scaled :", X_test_scaled.shape)
print("X_val shape   :", X_val.shape)

# 2. Labels
print("Unique y_train:", sorted(y_train.unique()))
print("Unique y_test :", sorted(y_test.unique()))

# 3. Tensor labels
print("Unique y_train_tensor:", y_train_tensor.unique().tolist())
print("Unique y_test_tensor :", y_test_tensor.unique().tolist())

# 4. Model output shape
model.eval()
with torch.no_grad():
    sample_logits = model(X_test_tensor[:5])
print("Model output shape:", sample_logits.shape)

# 5. Raw predictions
with torch.no_grad():
    raw_preds = torch.argmax(model(X_test_tensor), dim=1).cpu().numpy()
print("Unique raw preds (0–5):", np.unique(raw_preds))

# 6. Shifted predictions
shifted_preds = raw_preds + 1
print("Unique shifted preds (1–6):", np.unique(shifted_preds))

X_val_scaled = preprocessor.transform(X_val)

print("X_val shape (raw):", X_val.shape)
print("X_val_scaled shape (after preprocessing):", X_val_scaled.shape)

print("===  Convert X_val_scaled to tensor ===")

X_val_tensor = torch.tensor(X_val_scaled, dtype=torch.float32).to(DEVICE)

print("X_val_tensor shape:", X_val_tensor.shape)  # Expect (75, 12)

print("===  Load and train best model ===")

best_model = MLP_small(input_size, num_classes).to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(best_model.parameters(), lr=0.001)

epochs = 30
best_acc = 0.0
best_model_state = None

for epoch in range(epochs):
    best_model.train()
    total_loss = 0.0
    # Original (incorrect) code:
    # optimizer.zero_grad()
    # outputs = best_model(X_train_tensor)
    # loss = criterion(outputs, y_train_tensor)
    # loss.backward()
    # optimizer.step()

    # Corrected training loop using batches from train_loader
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()          # reset gradients
        outputs = best_model(X_batch)       # forward pass
        loss = criterion(outputs, y_batch)  # compute loss
        loss.backward()                # backpropagation
        optimizer.step()               # update weights

        total_loss += loss.item()

    # Evaluate current model performance
    current_acc = evaluate(best_model, test_loader)
    if current_acc > best_acc:
        best_acc = current_acc
        best_model_state = best_model.state_dict()

print("Training complete.")
print(f"Best accuracy achieved during training: {best_acc:.4f}")

# Load the best model state for final use
if best_model_state is not None:
    best_model.load_state_dict(best_model_state)
    print("Loaded best model state.")
else:
    print("Warning: Best model state was not saved. Using model from last epoch.")

print("===  Predict on X_val ===")

best_model.eval()
with torch.no_grad():
    logits_val = best_model(X_val_tensor)
    preds_val = torch.argmax(logits_val, dim=1).cpu().numpy()

print("Logits_val shape:", logits_val.shape)  # Expect (75, 6)
print("Unique raw preds (0–5):", np.unique(preds_val))

print("===  Shift predictions to 1–6 ===")

preds_val_shifted = preds_val + 1

print("Unique shifted preds (1–6):", np.unique(preds_val_shifted))

print("===  Export CSV ===")

df_pred = pd.DataFrame({
    "Id": np.arange(len(preds_val_shifted)),
    "Predicted_Type": preds_val_shifted
})

df_pred.to_csv("predictions_Cornelius_Yohaldere_Pred_DL.csv", index=False)

print("CSV saved as predictions_Cornelius_Yohaldere_Pred_DL.csv")
print(df_pred.head())

"""## Matrice de confusion et visualisation des prédicteurs"""

#Confusion Matrix and Evaluation on Public Test Set
print("===  Confusion Matrix on X_test ===")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
import matplotlib.pyplot as plt

# 1. Predict on X_test
best_model.eval()
all_preds_test = []
all_labels_test = []

with torch.no_grad():
    # Original (less robust) code:
    # logits_test = best_model(X_test_tensor)
    # preds_test = torch.argmax(logits_test, dim=1).cpu().numpy()

    # Corrected prediction loop using batches from test_loader
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.to(DEVICE)
        y_batch = y_batch.to(DEVICE)

        outputs = best_model(X_batch)
        _, predicted = torch.max(outputs, 1)

        all_preds_test.append(predicted.cpu().numpy())
        all_labels_test.append(y_batch.cpu().numpy())

y_true_test = np.concatenate(all_labels_test)
y_pred_test = np.concatenate(all_preds_test)

# 2. Shift predictions back to 1–6 (y_test is 1-indexed, y_true_test is 0-indexed)
preds_test_shifted = y_pred_test + 1

# 3. Compute confusion matrix (using 1-indexed y_test and shifted predictions)
cm = confusion_matrix(y_test, preds_test_shifted)

# 4. Display confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=sorted(y_test.unique()))
disp.plot(cmap="Blues")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix — Best Model on Public Test Set")
plt.tight_layout()
plt.show()

# 5. Classification report (using 1-indexed y_test and shifted predictions)
target_names_report = [f"Class {i}" for i in sorted(y_test.unique())]
print("\nClassification Report:")
print(classification_report(y_test, preds_test_shifted, target_names=target_names_report))